### ISSUE TITLE
lmfao

### ISSUE THREAD

**Issue by visualbasic6** [availproject/avail-core#101]
fantastic readme.md installation documentation here guys

and i love what you've done with https://www.docker.com/availj/avail:2.2.4.1

**Comment by visualbasic6** [comment]
don't label my legitimate submission as "spam"

docker doesn't work and readme.md has no installation docs

what is up with this project?

**Comment by Leouarz** [comment]
Your issue is title `lmfao`.
You're not in the correct repo.
No question or information given.

**Comment by visualbasic6** [comment]
"no question or information given" is a lie but i'm not going to argue all day with some person who thinks he's a full stack developer even though he can't code a blockchain from scratch

**Comment by Leouarz** [comment]
Yeah since you're not in the correct repo (the correct one being availproject/avail),  you did not follow the guidelines, describe your problems / errors, gave reproduction steps.  
What steps were not ok on the existing doc available in here ("using docker" section): https://docs.availproject.org/docs/operate-a-node/run-a-full-node/full-node

You are still welcome to put real issues with descriptive name and not "lmfao".

Due to the last, unnecessary words at the end, I will lock this issue now.
